---
new_page_extension: md
auto_deploy: false
admin_path: ''
webhook_url: 
sections:
- type: heading
  label: Content
- type: directory
  path: src/posts
  label: Posts
  create: documents
  match: "*.md"
  templates:
  - post
- type: heading
  label: Globals
- type: document
  path: src/_data/navigation.json
  label: Navigation
- type: document
  path: src/_data/tokens.json
  label: Theme settings
upload_dir: mooretech
public_path: " https://res.cloudinary.com/intergalactic-interactive/image/uploads"
front_matter_path: https://res.cloudinary.com/{{ CLOUD_NAME }}/image/upload
use_front_matter_path: false
file_template: ":filename:"
build:
  preview_env:
  - ELEVENTY_ENV=staging
  preview_output_directory: src/dist
  install_dependencies_command: npm install
  preview_docker_image: node:10
  mount_path: "/srv"
  working_dir: "/srv/src"
  instant_preview_command: npm start
